# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f59038d3e52b5d799f68f44c713d0aabd7c2cd1490dd81aee9881009bbea6f8afd330079ecb5d5e564d760a40eb70500454313d40993901e6562d2d6ec7ec86

test:
  secret_key_base: 42c9d5a31a739b5e6976f652e09f776f573164e7a6215d72e538e370a8455b2208f294ecaf52d1f12a8bc929ca839a0d44feec88e4b7445c6215b062de351aa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
